name: 🚀 Publish Packages to GitHub

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🍞 Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.11

      - name: Setup Node Registry for GitHub Packages
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ramolibre-core'

      - name: 🧶 Install Dependencies
        run: bun install --frozen-lockfile

      - name: 🔍 Run Tests
        run: bun test

      - name: 📦 Publish DSL Parser
        run: |
          cd packages/dsl-parser
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Hacemos lo mismo para el UI Themes
      - name: 🎨 Publish UI Themes
        run: |
          cd packages/ui-themes
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
